name = "MCMCTesting"
uuid = "9963b6a1-5d46-439c-8efc-3a487843c7fa"
authors = ["Ray Kim <msca8h@naver.com> and contributors"]
version = "1.0.0-DEV"

[deps]
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
HypothesisTests = "0.11"
Random = "1.9"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
